spring:
  application:
    name:
      spring-boot-lesson-3
    datasource:
      url: jdbc:h2:mem:test
      username: user_1
      password:
      driver-class-name: org.h2.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
