server:
  port: 8180
spring:
  application:
    name: issue-service
  datasource:
    url: jdbc:h2:mem:test
    username: kk
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: env, prometheus, health, info, metric